...started at Fri Jul 23 20:53:57 EDT 2021
Traceback (most recent call last):
  File "/storage/home/yur97/.local/lib/python3.6/site-packages/matlab/engine/__init__.py", line 45, in <module>
    pythonengine = importlib.import_module("matlabengineforpython"+_PYTHONVERSION)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'matlabengineforpython3_6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/storage/home/yur97/.local/lib/python3.6/site-packages/matlab/engine/__init__.py", line 61, in <module>
    pythonengine = importlib.import_module("matlabengineforpython"+_PYTHONVERSION)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'matlabengineforpython3_6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_histology_syn.py", line 2, in <module>
    import matlab.engine
  File "/storage/home/yur97/.local/lib/python3.6/site-packages/matlab/engine/__init__.py", line 64, in <module>
    'MathWorks Technical Support for assistance: %s' % e)
OSError: Please reinstall MATLAB Engine for Python or contact MathWorks Technical Support for assistance: No module named 'matlabengineforpython3_6'
...ended at Fri Jul 23 20:53:57 EDT 2021
