...started at Wed Jun  9 21:17:41 EDT 2021

======================================
  MutSigCV
  v1.4

  (c) Mike Lawrence and Gaddy Getz
  Broad Institute of MIT and Harvard
======================================


MutSigCV: PREPROCESS
--------------------
Loading mutation_file...
Loading coverage file...
Error using MutSigCVs_nbg>load_struct_specify_string_cols (line 1586)
../cov_out/cov_cohorts_060921_filtered/organ/Ovary.csv not found

Error in MutSigCVs_nbg>MutSig_preprocess (line 251)
  C = load_struct_specify_string_cols(coverage_file,1:3); % gene effect categ are all strings

Error in MutSigCVs_nbg (line 184)
  MutSig_preprocess(mutation_file,coverage_file,covariate_file,output_filestem,varargin{:})

Ovary
Traceback (most recent call last):
  File "run_organ_syn.py", line 37, in <module>
    runMutSigCV_syn(feat)
  File "run_organ_syn.py", line 34, in runMutSigCV_syn
    eng.MutSigCVs_nbg(maf,cov, covariates, outp, mut_dic, chain_f, nargout = 0)
  File "/storage/home/yur97/.local/lib/python3.6/site-packages/matlab/engine/matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "/storage/home/yur97/.local/lib/python3.6/site-packages/matlab/engine/futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "/storage/home/yur97/.local/lib/python3.6/site-packages/matlab/engine/fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: 
  File /gpfs/group/epo2/default/yur97/gitlab/pcawg-to-mutsigcv/mutsigsyn/MutSigCVs_nbg.m, line 1586, in load_struct_specify_string_cols

  File /gpfs/group/epo2/default/yur97/gitlab/pcawg-to-mutsigcv/mutsigsyn/MutSigCVs_nbg.m, line 251, in MutSig_preprocess

  File /gpfs/group/epo2/default/yur97/gitlab/pcawg-to-mutsigcv/mutsigsyn/MutSigCVs_nbg.m, line 184, in MutSigCVs_nbg
../cov_out/cov_cohorts_060921_filtered/organ/Ovary.csv not found

...ended at Wed Jun  9 21:18:25 EDT 2021
